version: '3.8'
services:
  pokemon:
    build:
      context: ./backend/pokemon
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres

  pokemon-details:
    build:
      context: ./backend/pokemon-details
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    depends_on:
      - postgres
      - pokemon

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      ports:
          - 15432:80
      volumes:
          - pgadmin:/var/lib/pgadmin
      networks:
        - postgres
      # depends_on:
      #   - database

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
    