server:
  port: 8085

spring:
  application:
    name: pokemon-details
  datasource:
    username: pokemon
    password: pokemon
    url: jdbc:postgresql://localhost:5432/pokemon
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show-sql: true






# Application Properties
POKEMON_SERVICE_URL: http://localhost:8080/api/v1/pokemon/all