server:
  ports: 8080
spring:
  application:
    name: pokemon
  datasource:
    username: pokemon
    password: pokemon
    url: jdbc:postgresql://localhost:5432/pokemon
  jpa:
    open-in-view: false
    hibernate:
      default_schema: public
      generate-ddl: true
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true

# Application Properties
POKEMON_API_BASEURL: https://pokeapi.co/api/v2/
POKEMON_LIST_ENDPOINT: pokemon?offset=0&limit=100
POKEMON_DETAIL_ENDPOINT: pokemon/
